export const ProductName = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
  { title: "2024", value: "2024" },
  { title: "2025", value: "2025" },
];

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];

export const footerLinks = [
  {
    title: "加入我们",
    links: [
      { title: "投递简历", url: "/" },
      { title: "合作", url: "/" },
      { title: "伙伴关系", url: "/" },
      { title: "商业关系", url: "/" },
    ],
  },
  {
    title: "企业信息",
    links: [
      { title: "事件", url: "/" },
      { title: "日报", url: "/" },
      { title: "产品", url: "/" },
      { title: "信用代码", url: "/" },
    ],
  },
  {
    title: "联系方式",
    links: [
      { title: "GitHub", url: "/" },
      { title: "微信公众号", url: "/" },
      { title: "抖音", url: "/" },
    ],
  },
];

// productData 格式
export const productData = [
  {
    id: 1,
    name: "马自达CX - 5",
    carConfiguration: {
      range: "200 - 300km",
      topSpeed: "180km/h",
      acceleration: "3s",
    },
    info: "马自达CX - 5是一款高性能、多功能的SUV，以其出色的性能和舒适的乘坐体验而闻名。",
    image: "/image/5.png",
    model: "/public/model/mazda - cx - 5",
  },
  {
    id: 2,
    name: "马自达3昂克赛拉",
    carConfiguration: {
      range: "350 - 450km",
      topSpeed: "200km/h",
      acceleration: "8s",
    },
    info: "马自达3昂克赛拉是一款时尚动感的紧凑型轿车，操控性能出色。",
    image: "/image/5.png",
    model: "/public/model/mazda - 3",
  },
  {
    id: 3,
    name: "马自达CX - 30",
    carConfiguration: {
      range: "250 - 350km",
      topSpeed: "190km/h",
      acceleration: "7s",
    },
    info: "马自达CX - 30是一款精致的小型SUV，兼具实用性和驾驶乐趣。",
    image: "/image/5.png",
    model: "/public/model/mazda - cx - 30",
  },
  {
    id: 4,
    name: "马自达CX - 8",
    carConfiguration: {
      range: "400 - 500km",
      topSpeed: "170km/h",
      acceleration: "9s",
    },
    info: "马自达CX - 8是一款中大型SUV，拥有宽敞的内部空间和豪华的配置。",
    image: "/image/5.png",
    model: "/public/model/mazda - cx - 8",
  },
  {
    id: 4,
    name: "马自达CX - 8",
    carConfiguration: {
      range: "400 - 500km",
      topSpeed: "170km/h",
      acceleration: "9s",
    },
    info: "马自达CX - 8是一款中大型SUV，拥有宽敞的内部空间和豪华的配置。",
    image: "/image/5.png",
    model: "/public/model/mazda - cx - 8",
  },
  {
    id: 5,
    name: "马自达CX - 8",
    carConfiguration: {
      range: "400 - 500km",
      topSpeed: "170km/h",
      acceleration: "9s",
    },
    info: "马自达CX - 8是一款中大型SUV，拥有宽敞的内部空间和豪华的配置。",
    image: "/image/5.png",
    model: "/public/model/mazda - cx - 8",
  },
  {
    id: 6,
    name: "马自达CX - 8",
    carConfiguration: {
      range: "400 - 500km",
      topSpeed: "170km/h",
      acceleration: "9s",
    },
    info: "马自达CX - 8是一款中大型SUV，拥有宽敞的内部空间和豪华的配置。",
    image: "/image/5.png",
    model: "/public/model/mazda - cx - 8",
  },
];

// infoData 格式
export const infoData = [
  {
    name: "马自达CX - 5",
    carConfiguration: {
      range: "200 - 300km",
      topSpeed: "180km/h",
      acceleration: "3s",
      seats: 5,
      bodyType: "SUV",
      kerbWeight: "1500kg",
      engineType: "自然吸气",
      engineDisplacement: "2.0L",
      power: "114kW",
      torque: "200N·m",
      transmissionType: "手自一体",
      frontSuspension: "麦弗逊式独立悬挂",
      rearSuspension: "多连杆式独立悬挂",
      steeringAssist: "电动助力转向",
      brakingType: "前碟刹后碟刹",
      brakingDistance: "100 - 0 km/h制动距离为42m",
      airbags: 6,
      ESC: "包含ABS、EBD等",
      activeBraking: "是",
      multimediaSystem: "支持蓝牙连接、USB接口、触摸屏",
      navigationSystem: "有",
      automaticAirConditioning: "是",
      seatMaterial: "真皮",
      sunroofType: "全景天窗",
      rimMaterial: "铝合金",
      tireSpecification: "225/65 R17",
    },
    info: "马自达CX - 5是一款高性能、多功能的SUV，以其出色的性能和舒适的乘坐体验而闻名。",
    image: "/image/mazda - cx - 5.jpg",
  },
  {
    name: "马自达3昂克赛拉",
    carConfiguration: {
      range: "350 - 450km",
      topSpeed: "200km/h",
      acceleration: "8s",
      seats: 5,
      bodyType: "轿车",
      kerbWeight: "1300kg",
      engineType: "自然吸气",
      engineDisplacement: "1.5L",
      power: "86kW",
      torque: "148N·m",
      transmissionType: "手自一体",
      frontSuspension: "麦弗逊式独立悬挂",
      rearSuspension: "扭力梁式非独立悬挂",
      steeringAssist: "电动助力转向",
      brakingType: "前碟刹后碟刹",
      brakingDistance: "100 - 0 km/h制动距离为40m",
      airbags: 6,
      ESC: "包含ABS、EBD等",
      activeBraking: "是",
      multimediaSystem: "支持蓝牙连接、USB接口、触摸屏",
      navigationSystem: "有",
      automaticAirConditioning: "是",
      seatMaterial: "织物",
      sunroofType: "普通天窗",
      rimMaterial: "铝合金",
      tireSpecification: "205/60 R16",
    },
    info: "马自达3昂克赛拉是一款时尚动感的紧凑型轿车，操控性能出色。",
    image: "/image/mazda - 3.jpg",
  },
  {
    name: "马自达CX - 30",
    carConfiguration: {
      range: "250 - 350km",
      topSpeed: "190km/h",
      acceleration: "7s",
      seats: 5,
      bodyType: "SUV",
      kerbWeight: "1400kg",
      engineType: "自然吸气",
      engineDisplacement: "2.0L",
      power: "114kW",
      torque: "200N·m",
      transmissionType: "手自一体",
      frontSuspension: "麦弗逊式独立悬挂",
      rearSuspension: "多连杆式独立悬挂",
      steeringAssist: "电动助力转向",
      brakingType: "前碟刹后碟刹",
      brakingDistance: "100 - 0 km/h制动距离为41m",
      airbags: 6,
      ESC: "包含ABS、EBD等",
      activeBraking: "是",
      multimediaSystem: "支持蓝牙连接、USB接口、触摸屏",
      navigationSystem: "有",
      automaticAirConditioning: "是",
      seatMaterial: "仿皮",
      sunroofType: "全景天窗",
      rimMaterial: "铝合金",
      tireSpecification: "215/55 R18",
    },
    info: "马自达CX - 30是一款精致的小型SUV，兼具实用性和驾驶乐趣。",
    image: "/image/mazda - cx - 30.jpg",
  },
  {
    name: "马自达CX - 8",
    carConfiguration: {
      range: "400 - 500km",
      topSpeed: "170km/h",
      acceleration: "9s",
      seats: 7,
      bodyType: "SUV",
      kerbWeight: "1800kg",
      engineType: "自然吸气",
      engineDisplacement: "2.5L",
      power: "141kW",
      torque: "252N·m",
      transmissionType: "手自一体",
      frontSuspension: "麦弗逊式独立悬挂",
      rearSuspension: "多连杆式独立悬挂",
      steeringAssist: "电动助力转向",
      brakingType: "前碟刹后碟刹",
      brakingDistance: "100 - 0 km/h制动距离为43m",
      airbags: 7,
      ESC: "包含ABS、EBD等",
      activeBraking: "是",
      multimediaSystem: "支持蓝牙连接、USB接口、触摸屏",
      navigationSystem: "有",
      automaticAirConditioning: "是",
      seatMaterial: "真皮",
      sunroofType: "全景天窗",
      rimMaterial: "铝合金",
      tireSpecification: "225/55 R19",
    },
    info: "马自达CX - 8是一款中大型SUV，拥有宽敞的内部空间和豪华的配置。",
    image: "/image/mazda - cx - 8.jpg",
  },
];
export const configData = {
  车身: [
    { id: "color1", name: "珍珠白", price: 1000, value: "#F5F5F5" },
    { id: "color2", name: "宝石蓝", price: 1500, value: "#2E5AAC" },
  ],
  车轮: [
    { id: "wheel1", name: "运动轮毂", price: 5000, value: "#333333" },
    { id: "wheel2", name: "豪华轮毂", price: 8000, value: "#555555" },
  ],
  内饰: [
    { id: "interior1", name: "真皮座椅", price: 12000, value: "#964B00" },
    { id: "interior2", name: "Alcantara", price: 15000, value: "#1A1A1A" },
  ],
  选装: [
    { id: "acc1", name: "高级音响", price: 8000, value: "#FFD700" },
    { id: "acc2", name: "自动驾驶", price: 20000, value: "#00FF00" },
  ],
};
// 基本信息          
// 整车性能
// 动力系统
// 地盘操控
// 轮毂/轮胎
// 舒适性配置
// 智能驾驶配置
// 外部配置
// 灯光配置
// 安全配置



export const pageSizeOptions = [10, 20, 50];