export interface ProductSPU {
  id: string;
  category_id: number;
  brand_id: number;
  name: string;
  product_sn: string;
  pic: string;
  photo_album: string[];
  price: number;
  promotion_price: number;
  promotion_start_time: string;
  promotion_end_time: string;
  sub_title: string;
  sales: number;
  unit: string;
  detail: Record<string, string>;
  publish_status: 0 | 1;
  new_status: 0 | 1;
  recommand_status: 0 | 1;
  create_time: string;
  is_deleted: 0 | 1;
}

export const initialProducts: ProductSPU[] = [
  {
    id: "1",
    category_id: 3,
    brand_id: 1,
    name: "小米 SU7",
    product_sn: "SU7-001",
    pic: "https://example.com/xiaomi-su7.jpg",
    photo_album: [
      "https://example.com/su7-album1.jpg",
      "https://example.com/su7-album2.jpg",
    ],
    price: 29999,
    promotion_price: 27999,
    promotion_start_time: "2024-10-01 00:00:00",
    promotion_end_time: "2024-10-31 23:59:59",
    sub_title: "高性能智能汽车",
    sales: 0,
    unit: "辆",
    detail: {
      电机类型: "后驱单电机",
      电池容量: "73.6kWh",
      CLTC续航: "668km",
      "0-100km/h加速": "5.28秒",
    },
    publish_status: 1,
    new_status: 1,
    recommand_status: 1,
    create_time: new Date().toISOString(),
    is_deleted: 0,
  },
  {
    id: "2",
    category_id: 3,
    brand_id: 1,
    name: "小米 SU7 Pro",
    product_sn: "SU7-Pro-002",
    pic: "https://example.com/xiaomi-su7-pro.jpg",
    photo_album: [
      "https://example.com/su7-pro-album1.jpg",
      "https://example.com/su7-pro-album2.jpg",
    ],
    price: 32999,
    promotion_price: 30999,
    promotion_start_time: "2024-10-01 00:00:00",
    promotion_end_time: "2024-10-31 23:59:59",
    sub_title: "长续航后驱单电机版",
    sales: 0,
    unit: "辆",
    detail: {
      电机类型: "后驱单电机",
      电池容量: "89.5kWh",
      CLTC续航: "800km",
      "0-100km/h加速": "5.7秒",
    },
    publish_status: 1,
    new_status: 1,
    recommand_status: 1,
    create_time: new Date().toISOString(),
    is_deleted: 0,
  },
  {
    id: "3",
    category_id: 3,
    brand_id: 1,
    name: "小米 SU7 Max",
    product_sn: "SU7-Max-003",
    pic: "https://example.com/xiaomi-su7-max.jpg",
    photo_album: [
      "https://example.com/su7-max-album1.jpg",
      "https://example.com/su7-max-album2.jpg",
    ],
    price: 35999,
    promotion_price: 33999,
    promotion_start_time: "2024-10-01 00:00:00",
    promotion_end_time: "2024-10-31 23:59:59",
    sub_title: "双电机全轮驱动性能版",
    sales: 0,
    unit: "辆",
    detail: {
      电机类型: "双电机全轮驱动",
      电池容量: "101kWh",
      CLTC续航: "1000km",
      "0-100km/h加速": "3.9秒",
    },
    publish_status: 1,
    new_status: 1,
    recommand_status: 1,
    create_time: new Date().toISOString(),
    is_deleted: 0,
  },
  {
    id: "4",
    category_id: 3,
    brand_id: 1,
    name: "小米 SU7 Ultra",
    product_sn: "SU7-Ultra-004",
    pic: "https://example.com/xiaomi-su7-ultra.jpg",
    photo_album: [
      "https://example.com/su7-ultra-album1.jpg",
      "https://example.com/su7-ultra-album2.jpg",
    ],
    price: 39999,
    promotion_price: 37999,
    promotion_start_time: "2024-10-01 00:00:00",
    promotion_end_time: "2024-10-31 23:59:59",
    sub_title: "极致性能全轮驱动版",
    sales: 0,
    unit: "辆",
    detail: {
      电机类型: "双电机全轮驱动",
      电池容量: "101kWh",
      CLTC续航: "1000km",
      "0-100km/h加速": "3.2秒",
    },
    publish_status: 1,
    new_status: 1,
    recommand_status: 1,
    create_time: new Date().toISOString(),
    is_deleted: 0,
  },
  {
    id: "5",
    category_id: 3,
    brand_id: 1,
    name: "小米 YU7",
    product_sn: "YU7-005",
    pic: "https://example.com/xiaomi-yu7.jpg",
    photo_album: [
      "https://example.com/yu7-album1.jpg",
      "https://example.com/yu7-album2.jpg",
    ],
    price: 25999,
    promotion_price: 23999,
    promotion_start_time: "2024-10-01 00:00:00",
    promotion_end_time: "2024-10-31 23:59:59",
    sub_title: "入门级智能电动轿车",
    sales: 0,
    unit: "辆",
    detail: {
      电机类型: "后驱单电机",
      电池容量: "62kWh",
      CLTC续航: "500km",
      "0-100km/h加速": "6.5秒",
    },
    publish_status: 1,
    new_status: 1,
    recommand_status: 1,
    create_time: new Date().toISOString(),
    is_deleted: 0,
  },
  {
    id: "6",
    category_id: 3,
    brand_id: 1,
    name: "小米 YU7 Pro",
    product_sn: "YU7-Pro-006",
    pic: "https://example.com/xiaomi-yu7-pro.jpg",
    photo_album: [
      "https://example.com/yu7-pro-album1.jpg",
      "https://example.com/yu7-pro-album2.jpg",
    ],
    price: 28999,
    promotion_price: 26999,
    promotion_start_time: "2024-10-01 00:00:00",
    promotion_end_time: "2024-10-31 23:59:59",
    sub_title: "长续航智能电动轿车",
    sales: 0,
    unit: "辆",
    detail: {
      电机类型: "后驱单电机",
      电池容量: "75kWh",
      CLTC续航: "650km",
      "0-100km/h加速": "6.0秒",
    },
    publish_status: 1,
    new_status: 1,
    recommand_status: 1,
    create_time: new Date().toISOString(),
    is_deleted: 0,
  },
  {
    id: "7",
    category_id: 3,
    brand_id: 1,
    name: "小米 YU7 Max",
    product_sn: "YU7-Max-007",
    pic: "https://example.com/xiaomi-yu7-max.jpg",
    photo_album: [
      "https://example.com/yu7-max-album1.jpg",
      "https://example.com/yu7-max-album2.jpg",
    ],
    price: 31999,
    promotion_price: 29999,
    promotion_start_time: "2024-10-01 00:00:00",
    promotion_end_time: "2024-10-31 23:59:59",
    sub_title: "双电机长续航版",
    sales: 0,
    unit: "辆",
    detail: {
      电机类型: "双电机全轮驱动",
      电池容量: "85kWh",
      CLTC续航: "800km",
      "0-100km/h加速": "4.5秒",
    },
    publish_status: 1,
    new_status: 1,
    recommand_status: 1,
    create_time: new Date().toISOString(),
    is_deleted: 0,
  },
  // 这里可以继续添加其他产品数据
  {
    id: "8",
    category_id: 3,
    brand_id: 1,
    name: "小米 YU7 Ultra",
    product_sn: "YU7-Ultra-008",
    pic: "https://example.com/xiaomi-yu7-ultra.jpg",
    photo_album: [
      "https://example.com/yu7-ultra-album1.jpg",
      "https://example.com/yu7-ultra-album2.jpg",
    ],
    price: 34999,
    promotion_price: 32999,
    promotion_start_time: "2024-10-01 00:00:00",
    promotion_end_time: "2024-10-31 23:59:59",
    sub_title: "高性能双电机全轮驱动版",
    sales: 0,
    unit: "辆",
    detail: {
      电机类型: "双电机全轮驱动",
      电池容量: "90kWh",
      CLTC续航: "900km",
      "0-100km/h加速": "4.0秒",
    },
    publish_status: 1,
    new_status: 1,
    recommand_status: 1,
    create_time: new Date().toISOString(),
    is_deleted: 0,
  },
];
